# Auto-generated by 
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/home/totsugekitai/workspace/mywork/minos/edk2
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/home/totsugekitai/workspace/mywork/minos/edk2/BaseTools
fi
if [ -e /home/totsugekitai/workspace/mywork/minos/edk2/BaseTools/Bin/Linux-x86_64 ]
then
  if [ ${PATH//home/totsugekitai/workspace/mywork/minos/edk2/BaseTools/Bin/Linux-x86_64/} == $PATH ]
  then
    export PATH=/home/totsugekitai/workspace/mywork/minos/edk2/BaseTools/Bin/Linux-x86_64:$PATH
  fi
fi
